// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtccaljxzqmzqtswnuim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Y2NhbGp4enFtenF0c3dudWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNDQ4MDMsImV4cCI6MjA4NzkyMDgwM30.VV3ljdRDyHQzxymh2s3x3o5TQVqrJ34MZ9Tg4ZOYo_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});